# TAP results for test_unittest_not_shown_in_traceback.py
not ok 1 - test_unittest_not_shown_in_traceback.py::t.test_hello
# 
# self = <test_unittest_not_shown_in_traceback.t testMethod=test_hello>
# 
#     def test_hello(self):
#         x = 3
# >       self.assertEqual(x, 4)
# E       AssertionError: 3 != 4
# 
# test_unittest_not_shown_in_traceback.py:5: AssertionError
1..1
